<?php

declare(strict_types=1);

namespace ScAlwaysdata\Tests\Service;

use PHPUnit\Framework\TestCase;
use ScAlwaysdata\Service\RobotsTxtService;

class RobotsTxtServiceTest extends TestCase
{
    private const PS_ROBOTS = "# robots.txt automatically generated by PrestaShop\nUser-agent: *\nDisallow: /*?q=\n";

    private string $dir;

    private string $robots;

    protected function setUp(): void
    {
        $this->dir = sys_get_temp_dir() . '/robots_test_' . uniqid();
        mkdir($this->dir);
        $this->robots = $this->dir . '/robots.txt';
        \Configuration::$testValues = ['SC_ALWAYSDATA_HTACCESS_PATH' => $this->dir . '/.htaccess'];
    }

    protected function tearDown(): void
    {
        foreach (glob($this->dir . '/*') as $f) {
            @unlink($f);
        }
        @rmdir($this->dir);
    }

    private function service(): RobotsTxtService
    {
        return new RobotsTxtService();
    }

    public function testRobotsPathIsNextToHtaccess(): void
    {
        $this->assertSame($this->robots, $this->service()->getRobotsPath());
    }

    public function testReadSettingsReturnsDefaultsWhenNeverConfigured(): void
    {
        file_put_contents($this->robots, self::PS_ROBOTS);

        $settings = $this->service()->readSettings();

        $this->assertFalse($settings['configured']);
        $this->assertFalse($settings['enabled']);
        $this->assertSame(RobotsTxtService::DEFAULT_DISALLOW, $settings['disallow']);
        $this->assertSame(RobotsTxtService::DEFAULT_BOTS, $settings['bots']);
        $this->assertFalse($settings['in_file']);
    }

    public function testSaveAndApplyAppendsBlockAfterPrestashopContent(): void
    {
        file_put_contents($this->robots, self::PS_ROBOTS);

        $this->service()->saveAndApply(true, ['/*resultsPerPage='], ['AhrefsBot']);

        $this->assertSame(
            self::PS_ROBOTS . "\n"
            . "# BEGIN sc_alwaysdata robots\n"
            . "# Managed by sc_alwaysdata (Back-office > Scriptami > Alwaysdata). Manual edits are overwritten.\n"
            . "User-agent: *\n"
            . "Disallow: /*resultsPerPage=\n"
            . "\n"
            . "User-agent: AhrefsBot\n"
            . "Disallow: /\n"
            . "# END sc_alwaysdata robots\n",
            file_get_contents($this->robots)
        );
    }

    public function testSaveAndApplyReplacesBlockWithoutDuplicating(): void
    {
        file_put_contents($this->robots, self::PS_ROBOTS);

        $this->service()->saveAndApply(true, ['/*a='], ['AhrefsBot']);
        $this->service()->saveAndApply(true, ['/*b='], []);

        $content = file_get_contents($this->robots);
        $this->assertSame(1, substr_count($content, '# BEGIN sc_alwaysdata robots'));
        $this->assertStringContainsString('Disallow: /*b=', $content);
        $this->assertStringNotContainsString('/*a=', $content);
        $this->assertStringNotContainsString('AhrefsBot', $content);
    }

    public function testDisablingRemovesBlockAndRestoresOriginalFile(): void
    {
        file_put_contents($this->robots, self::PS_ROBOTS);
        $this->service()->saveAndApply(true, ['/*a='], ['AhrefsBot']);

        $this->service()->saveAndApply(false, ['/*a='], ['AhrefsBot']);

        $this->assertSame(self::PS_ROBOTS, file_get_contents($this->robots));
        $settings = $this->service()->readSettings();
        $this->assertTrue($settings['configured']);
        $this->assertFalse($settings['enabled']);
        $this->assertSame(['/*a='], $settings['disallow'], 'Lists are kept when disabled');
    }

    public function testSettingsRoundTripAndDeduplication(): void
    {
        file_put_contents($this->robots, self::PS_ROBOTS);

        $this->service()->saveAndApply(true, [' /*a= ', '', '/*a='], ['AhrefsBot', 'ahrefsbot', ' ']);

        $settings = $this->service()->readSettings();
        $this->assertTrue($settings['in_file']);
        $this->assertSame(['/*a='], $settings['disallow']);
        $this->assertSame(['AhrefsBot'], $settings['bots']);
    }

    public function testBuildConfiguredBlockIsEmptyWhenDisabled(): void
    {
        file_put_contents($this->robots, self::PS_ROBOTS);
        $this->service()->saveAndApply(false, ['/*a='], []);

        $this->assertSame('', $this->service()->buildConfiguredBlock());
    }

    public function testSaveAndApplyCreatesBackup(): void
    {
        file_put_contents($this->robots, self::PS_ROBOTS);

        $this->service()->saveAndApply(true, ['/*a='], []);

        $this->assertNotEmpty(glob($this->robots . '.*.bak'));
    }

    public function testRejectsDisallowPathWithNewline(): void
    {
        file_put_contents($this->robots, self::PS_ROBOTS);

        $this->expectException(\InvalidArgumentException::class);
        $this->service()->saveAndApply(true, ["/*a=\nUser-agent: *\nDisallow: /"], []);
    }

    public function testRejectsWildcardBot(): void
    {
        file_put_contents($this->robots, self::PS_ROBOTS);

        // "User-agent: * / Disallow: /" would deindex the whole shop
        $this->expectException(\InvalidArgumentException::class);
        $this->service()->saveAndApply(true, [], ['*']);
    }

    public function testMissingRobotsFileThrows(): void
    {
        $this->expectException(\RuntimeException::class);
        $this->service()->saveAndApply(true, ['/*a='], []);
    }

    public function testAddBotsEnablesBlockAndKeepsExistingLists(): void
    {
        file_put_contents($this->robots, self::PS_ROBOTS);
        $this->service()->saveAndApply(false, ['/*?q='], ['AhrefsBot']);

        $this->service()->addBots(['GPTBot', 'ahrefsbot']);

        $settings = $this->service()->readSettings();
        $this->assertTrue($settings['enabled']);
        $this->assertTrue($settings['in_file']);
        $this->assertSame(['/*?q='], $settings['disallow']);
        $this->assertSame(['AhrefsBot', 'GPTBot'], $settings['bots']);
    }
}
