services:
  _defaults:
    public: true
    autowire: false
    autoconfigure: false

  # Services
  ScAlwaysdata\Service\LogReaderService:
    class: ScAlwaysdata\Service\LogReaderService

  ScAlwaysdata\Service\CrawlerAnalyserService:
    class: ScAlwaysdata\Service\CrawlerAnalyserService

  ScAlwaysdata\Service\PhpErrorAnalyserService:
    class: ScAlwaysdata\Service\PhpErrorAnalyserService

  ScAlwaysdata\Service\HtaccessService:
    class: ScAlwaysdata\Service\HtaccessService

  ScAlwaysdata\Service\HttpLogParserService:
    class: ScAlwaysdata\Service\HttpLogParserService
    arguments:
      - '@ScAlwaysdata\Service\CrawlerAnalyserService'

  # Controller
  sc_alwaysdata.controller.sc_alwaysdata:
    class: ScAlwaysdata\Controller\Admin\ScAlwaysdataController
    arguments:
      - '@ScAlwaysdata\Service\LogReaderService'
      - '@ScAlwaysdata\Service\CrawlerAnalyserService'
      - '@ScAlwaysdata\Service\PhpErrorAnalyserService'
      - '@ScAlwaysdata\Service\HtaccessService'
    calls:
      - [setContainer, ['@service_container']]
